### PR TITLE
Misc bug/style/display fixes, deleting all "delete all" servlets and buttons

### LINKED ISSUE #74: Event Display on Map
Event tab section does not display "No Events to Show" when there are no events to show

### LINKED ISSUE #76: Event Time Display
When events start and end on the same day their time should display (for ex) Fri Jul 17, 2020 startTime-endTime timeZone 
but right now they are displaying as if they end on different days (Fri Jul 17, 2020 startTime - Fri Jul 17, 2020 endTime timeZone

### PR DESCRIPTION
**Pull request by lexidelorey**
fixes #74 
fixes #76

### CODE REVIEW

**Comment by lexidelorey** [comment]
The last commit is the only one that is relevant to this pull request. The others were already submitted in pull 68

File: src/main/java/com/google/sps/data/Post.java [hunk 1]
```diff
@@ -3,13 +3,20 @@
...
 public final class Post {
+  private long id;
   private String caption;
   private BlobKey blobKey;
   private String creator;
+  private String location;
+  private String placeId;
 
-  public Post(String caption, BlobKey blobKey, String creator) {
+  public Post(long id, String caption, BlobKey blobKey, String creator,
```
Comment (usaeedw) [inline src/main/java/com/google/sps/data/Post.java]: The recommended way to break methods with a large number of arguments is as follows: 

```java
public Post(
    long id, 
    String caption, 
    BlobKey blobKey, 
    String creator, 
    String location, 
    String placeId) {
```

The external style guide doesn't show any examples, but we use this internally. 

More generally, we try to avoid constructors that take this many arguments, and instead use the `Builder` pattern. See [this](https://howtodoinjava.com/design-patterns/creational/builder-pattern-in-java/) for an overview. The book "Effective Java" has a great overview of this pattern.

File: src/main/java/com/google/sps/servlets/EventServlet.java [hunk 2]
```diff
@@ -38,19 +38,25 @@ public void doPost(HttpServletRequest request, HttpServletResponse response) thr
     String requestEndTime = request.getParameter(Constants.END_TIME_PARAM);
     String timeZone = request.getParameter(Constants.TIME_ZONE_PARAM);
 
-    //create dates from input
-    Date startDate = createDateTime(requestStartDate.substring(0, 4),
+    //create dates with times from input for time verification
```
Comment (usaeedw) [inline src/main/java/com/google/sps/servlets/EventServlet.java]: Please add a space between // and the start of the sentence. 

Nit: Use sentence case.

**Review by usaeedw — CHANGES_REQUESTED** [review]

File: src/main/webapp/postScript.js [hunk 3]
```diff
@@ -39,11 +50,59 @@ function createPost(post) {
...
+  }).then(postElement.style.display = "none")
+    .then(getPosts());
+}
+
+function deleteAllPosts() {
+  fetch('/post')
+    .then(response => response.json())
+    .then(posts => {
+      for (i = 0; i < posts.length; i ++) {
+        console.log(posts[i].blobKey);
```
Comment (ellisvivian) [inline src/main/webapp/postScript.js]: Nit: Is this print statement still needed?

**Review by ellisvivian — DISMISSED** [review]

File: src/main/java/com/google/sps/servlets/EventServlet.java [hunk 4]
```diff
@@ -38,19 +38,25 @@ public void doPost(HttpServletRequest request, HttpServletResponse response) thr
...
+    Date startDateTime = createDateTime(requestStartDate.substring(0, 4),
           requestStartDate.substring(5, 7), requestStartDate.substring(8), 
           requestStartTime, timeZone); 
-    Date endDate = createDateTime(requestEndDate.substring(0, 4), 
+    Date endDateTime = createDateTime(requestEndDate.substring(0, 4),
```
Comment (usaeedw) [inline src/main/java/com/google/sps/servlets/EventServlet.java]: All these numbers make the code difficult to read and parse. E.g. I have no idea whether this code is correct. 

Also, it seems the exact sequence of code is repeated below.

Suggestion:

Create a method called `parseDate` (or something more appropriate), and move all this code inside it.
Within the method, use an example date to document how this date is being parsed.

File: src/main/java/com/google/sps/data/Post.java (hunk 1 above)
Comment (usaeedw) [reply src/main/java/com/google/sps/data/Post.java]: Same applies to other code locations in this PR.

File: src/main/webapp/eventScript.js [hunk 5]
```diff
@@ -181,12 +181,19 @@ function getPublicEvents() {
...
+        noEventElement = document.createElement('p');
+        noEventElement.innerText = "No events to show.";
+        eventDivElement.appendChild(noEventElement);
+      }
+      else {
+        for (i = 0; i < events.length; i++) {
+          if (events[i].location == locationName 
+              && events[i].privacy == "public") {
+              eventDivElement.appendChild(createEventNoResponse(events[i]));
+            }
```
Comment (usaeedw) [inline src/main/webapp/eventScript.js]: This  } needs to line up with the if.

File: src/main/java/com/google/sps/servlets/EventServlet.java (hunk 2 above)
Comment (usaeedw) [reply src/main/java/com/google/sps/servlets/EventServlet.java]: Same for other locations in this PR.

**Review by usaeedw — DISMISSED** [review]

**Review by Omarzintan — APPROVED** [review]

**Review by Omarzintan — APPROVED** [review]
